---
- hosts: 172.31.35.66
  become: yes
  tasks:
    - name: install git
      apt:
        name: git
        state: present

    - name: install tree     
      apt:  
        name: treeee
        state: present
      ignore_errors: yes

    - name: install wget
      apt:
        name: wget
        state: present
