---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks: 
    - name: Install git 
      apt:
         name: git 
         state: present
      when: ansible_os_family == "Debian"
    - name: Install tree
      apt:
        name: tree
        state: present
      when: ansible_os_family == "Debian"  

    - name: Install wget 
      apt: 
        name: wget
        state: present
      when: ansible_os_family == "Debian"  

    - name : Install apache2 on ubuntu
      apt:
        name: "{{mywebpackforununtu}}"
        state: present
      when: ansible_os_family == "Debian" 
    
    - name : Install httpd on Redhat
      yum:
        name: "{{mywebpackforredhat}}"
        state: present
      when: ansible_os_family == "RedHat" 

