---
- hosts: 172.31.35.66
  become: yes
  tasks:
    - name: install git
      apt:
        name: git
        state: present
      tags: onlygit

    - name: install tree     
      apt:  
        name: tree
        state: present
      tags: onlytree

    - name: install wget
      apt:
        name: wget
        state: present
      tags: onlywget 
