---
- hosts: 172.31.35.66
  become: yes
  tasks:
  - include_tasks: mytasks.yml
  - name: install apache2 on my ubuntu node
    apt:
      name: apache2
      state: present
  - name: copy from myindex.j2 to index.html
    template:
      src: myindex.j2
      dest: /var/www/html/index.html     