---
- hosts: all
  become: yes
  tasks:
    - name: unistall git
      apt:
        name: git
        state: absent
    - name: uninstall tree
      apt:
        name: tree
        state: absent
    - name: uninstall wget
      apt:
        name: wget
        state: absent
    - name: install webserver
      apt:
        name: apache2
        state: present


