--- 
- hosts: mywebserver
  become: yes
  vars:
      myvar1: git 
      myvar2: tree
      myvar3: wget 

  tasks:
    - name: Install git 
      apt: 
        name: "{{myvar1}}"
        state: present
      when: ansible_os_family == "Debian"  